### ISSUE TITLE
Deserialization not working for lower camel case

### ISSUE THREAD

**Issue by kedrzu** [simple-odata-client/Simple.OData.Client#489] opened 2018-06-11 16:05 UTC
When I configure OData endpoint to use lower camel case naming conventions, I have a problem with `Simple.OData.Client`: object deserialization does not work.

Strange thing is, that everything except that works flawlessly, i.e. client is building queries with filters, selects and expands as it should be - using lower camel case. Then when mapping response to objects, it does not map any properties. The number of objects returned is correct, but they all have empty props.

I tried to change `INameMatchResolver` without any luck.

**Comment by object** [comment] 2018-06-13 05:51
That's weird of course. I will look into it.

**Comment by dzins** [comment] 2019-02-02 06:49
I just ran in to this same problem, looks like it's still marked as needs information?

**Comment by Nomi90** [comment] 2019-02-24 08:20
I am getting the same issue. it resolved?

**Comment by object** [comment] 2019-02-24 09:25
I have reproduce the issue. Will let you know once it's fixed.

**Comment by ysmoradi** [comment] 2019-04-25 07:43
I've ran to the same issue )-:

**Comment by object** [comment] 2019-04-26 12:55
@phatcher I created branch "name-resolver" to work on this issue. I appreciate if you can have a look and suggest how custom name resolution policy can be applied to TypeCache. Here's what I did:
1. Created failing unit tests for this issue (they overried NameMatchResolver)
2. Renamed TypeHelper class to TypeCacheResolver (IMHO it better reflects its purpose)
3. Added INameMatchResolver member variable to TypeCacheResolver.
4. Temporarily set it to NotStrict

Now tests pass. So what I am trying to figure out is how to propagate NameMatchResolver value from ODataClientSettings (in session object) to TypeCache -> TypeCacheResolver). Do you have any suggestions?

**Comment by object** [comment] 2019-04-28 07:21
@phatcher I believed the issue is fixed now. I updated type cache to use name resolver from the current session. I also removed global type cache because it was used only in tests.

**Comment by object** [comment] 2019-04-28 07:31
Finally this bug is fixed and I plan to release version 5.7 within a day or two.

**Comment by object** [comment] 2019-04-29 12:11
Released version 5.7.

**Closed by object** 2019-04-29 12:11 UTC
Labels: bug, implemented
