### ISSUE TITLE
Filtering by Enum as a numeric values

### ISSUE THREAD

**Issue by AmirImam** [simple-odata-client/Simple.OData.Client#606] opened 2019-04-15 11:18 UTC
Hi 
I am working on API with OData V3.
I want to make a query with a enum value .. the normal thing that I know that the enum is a numeric values .. so if I want to use it in a filter I have to send it like that
`$filter=PatientDetectingState eq 1`
but this filter throws an error:

> "The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand types 'Edm.String' and 'Edm.Int32' for operator kind 'Equal'

But if the filter was like this:
`$filter=PatientDetectingState eq '1'`
it works fine.
Ten enum field type is a Edm.String in metadata .. why ?!!

![Capture](https://user-images.githubusercontent.com/26382843/56128733-cbbb1980-5f80-11e9-9997-b36cf6cbbc3c.PNG)

Now I need to make my filter in Simple.OData.Client like that
```
obj.Filter(it=> it.PatientDetectingState == PatientDetectingStates.Closed)
.FindEntriesAsync()
```

I tried to [this ](https://github.com/simple-odata-client/Simple.OData.Client/issues/159) but I don't understand 'revise your service metadata' means

I tried 
`config.EnableEnumPrefixFree(true);` in WebApiConfig.cs but didn't work

I tried [this ](http://odata.github.io/WebApi/02-02-model-builder-untyped/) but didn't work either 

How can I do it ?
I am working on

- Microsoft.AspNet.WebApi.OData 5.2.3
- Simple.OData.Client 5.6.2
- Microsoft.Data.OData 5.8.4

**Comment by object** [comment] 2019-04-29 13:01
Looks like the problem is caused by PatientDetectingState property definition. It is assigned to Edm.String, not the actual enum type.

If you check OData TripPin sample, you will see that for Person entity type has "Gender" property assigned to a proper enum type:

Property Name="Gender" Type="Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender" Nullable="false"

As long as it is set to a string, you can't use it as enum in your queries.

**Comment by AmirImam** [comment] 2019-04-29 18:44
> Looks like the problem is caused by PatientDetectingState property definition. It is assigned to Edm.String, not the actual enum type.
> 
> If you check OData TripPin sample, you will see that for Person entity type has "Gender" property assigned to a proper enum type:
> 
> Property Name="Gender" Type="Microsoft.OData.Service.Sample.TrippinInMemory.Models.PersonGender" Nullable="false"
> 
> As long as it is set to a string, you can't use it as enum in your queries.

Yes I think this is the problem. But I don't know how to change it and assign it to it's type.

**Comment by object** [comment] 2019-04-29 20:30
This has to be done on a server side. Simple.OData.Client only deals with client-side request generation.

**Comment by uthaman1** [comment] 2019-05-06 18:46
Thanks @object. I have the same question as @AmirImam. How do you assign to a proper enum type on the server side?

For example, I have the following:

`
public enum Status
{
    One,
    Two,
    Three
}
`

`
public class Entity
{
    public Status Status { get; set; }
}
`

`
ODataModelBuilder builder = new ODataConventionModelBuilder();
`
`
builder.EntitySet<Entity>("entities");
`
`
IEdmModel model = builder.GetEdmModel();
`

**Comment by object** [comment] 2019-05-06 19:18
You can check official OData samples: https://github.com/OData/ODataSamples
For example, TripPin sample implements OData enums.

**Comment by uthaman1** [comment] 2019-05-06 21:07
Thanks @object. Looks like that's for OData V4. I have V4 working I'm looking for pointers for OData V3.

**Closed** 2020-02-19 17:12 UTC
Labels: invalid
